# -*- coding: utf-8 -*-
"""text summarization using bart a deep learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ou9gkFjdg-NwB0Xjyf59fC9D7QZ1m8sc
"""

from transformers import BartForConditionalGeneration, BartTokenizer

def summarize_text(text):
    # Load pre-trained model and tokenizer from Hugging Face
    model_name = "facebook/bart-large-cnn"
    tokenizer = BartTokenizer.from_pretrained(model_name)
    model = BartForConditionalGeneration.from_pretrained(model_name)

    # Tokenize input text
    inputs = tokenizer.encode("summarize: " + text, return_tensors="pt", max_length=1024, truncation=True)

    # Generate summary
    summary_ids = model.generate(inputs, max_length=150, min_length=50, length_penalty=2.0, num_beams=4, early_stopping=True)

    # Decode and return the summary
    summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
    return summary

# Example usage
text = """
College serves as a significant period of growth and discovery, providing students not only with academic knowledge but also with a variety of experiences that shape their identity and future. Academically, college offers a depth of study that allows students to delve deeply into subjects they are passionate about, often with the guidance of experienced professors who inspire curiosity and critical thinking. The curriculum is designed not just to impart knowledge but to develop essential skills, such as problem-solving, effective communication, and analytical thinking, which are crucial in today’s dynamic workforce.

Beyond the classroom, college is a social environment where students meet peers from diverse backgrounds, cultures, and perspectives. These interactions are valuable, fostering empathy, open-mindedness, and intercultural understanding. Many students build friendships that last a lifetime, creating a support network that continues well after graduation. The college setting encourages students to participate in extracurricular activities, from sports teams and student organizations to volunteer work and internships. These opportunities provide a well-rounded experience, allowing students to apply what they learn in real-world settings, discover new interests, and develop leadership and teamwork skills.

College is also a time of self-discovery. Living independently for the first time, students learn practical life skills, such as managing finances, balancing responsibilities, and making decisions that impact their futures. This autonomy helps build resilience and confidence, teaching students to navigate challenges and embrace their individuality. Ultimately, college is a journey of personal and intellectual growth, equipping students not only with knowledge but with the adaptability, self-awareness, and skills needed to make a meaningful impact in their chosen careers and communities.
"""

summary = summarize_text(text)
print("Summary:", summary)

"""text summarization usnig machine learning ** text summarization **

"""

!pip install ipywidgets

from transformers import BartForConditionalGeneration, BartTokenizer
import ipywidgets as widgets
from IPython.display import display

# Load pre-trained model and tokenizer from Hugging Face
model_name = "facebook/bart-large-cnn"
tokenizer = BartTokenizer.from_pretrained(model_name)
model = BartForConditionalGeneration.from_pretrained(model_name)

def summarize_text(text):
    # Tokenize input text
    inputs = tokenizer.encode("summarize: " + text, return_tensors="pt", max_length=1024, truncation=True)

    # Generate summary
    summary_ids = model.generate(inputs, max_length=150, min_length=50, length_penalty=2.0, num_beams=4, early_stopping=True)

    # Decode and return the summary
    summary = tokenizer.decode(summary_ids[0], skip_special_tokens=True)
    return summary

# Create widgets
text_input = widgets.Textarea(
    value='',
    placeholder='Enter text to summarize...',
    description='Input:',
    layout=widgets.Layout(width='100%', height='150px')
)

output_area = widgets.Output()
summarize_button = widgets.Button(description="Summarize")

def on_button_click(b):
    with output_area:
        output_area.clear_output()  # Clear previous output
        text = text_input.value
        if text:
            summary = summarize_text(text)
            print("Summary:", summary)
        else:
            print("Please enter some text to summarize.")

# Link button click event to function
summarize_button.on_click(on_button_click)

# Display the widgets
display(text_input, summarize_button, output_area)

!sudo apt-get install xvfb